// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadData() {
  return window['go']['main']['App']['LoadData']();
}

export function SaveData(arg1) {
  return window['go']['main']['App']['SaveData'](arg1);
}
