// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadData():Promise<string>;

export function SaveData(arg1:string):Promise<void>;
